#!/usr/bin/env bash
# This script:
# * makes CA certs and keys
# * makes keys and CSRs for client/server
# * uses the CA keys to sign the client/server CSRs

openssl ecparam -name prime256v1 -out nistp256.pem
openssl ecparam -name secp384r1 -out nistp384.pem

# CA
openssl req -nodes \
          -x509 \
          -newkey ec:nistp384.pem \
          -keyout ca.key \
          -out ca.cert \
          -sha256 \
          -batch \
          -days 3650 \
          -subj "/CN=somerootca ECDSA CA"

# server
openssl req -nodes \
          -newkey ec:nistp256.pem \
          -keyout server.key \
          -out server.req \
          -sha256 \
          -batch \
          -days 2000 \
          -subj "/CN=jobserver.com"

# client 'alice'
openssl req -nodes \
          -newkey ec:nistp384.pem \
          -keyout alice.key \
          -out alice.req \
          -sha256 \
          -batch \
          -days 2000 \
          -subj "/CN=alice+/UID=alice"

# sign server cert
openssl x509 -req \
        -in server.req \
        -out server.cert \
        -CA ca.cert \
        -CAkey ca.key \
        -sha256 \
        -days 2000 \
        -set_serial 456 \
        -extensions v3_end -extfile openssl.cnf

openssl x509 -req \
        -in alice.req \
        -out alice.cert \
        -CA ca.cert \
        -CAkey ca.key \
        -sha256 \
        -days 2000 \
        -set_serial 789 \
        -extensions v3_client -extfile openssl.cnf

cat ca.cert > server.chain
cat server.cert ca.cert > server.fullchain

cat ca.cert > alice.chain
cat alice.cert ca.cert > alice.fullchain

openssl asn1parse -in ca.cert -out ca.der > /dev/null

