#!/usr/bin/env bash
# This script:
# * makes CA certs and keys
# * makes keys and CSRs for client/server
# * uses the CA keys to sign the client/server CSRs

openssl ecparam -name prime256v1 -out nistp256.pem
openssl ecparam -name secp384r1 -out nistp384.pem

# CA
openssl req -nodes \
          -x509 \
          -newkey ec:nistp384.pem \
          -keyout ca.key \
          -out ca.pem \
          -sha256 \
          -batch \
          -days 3650 \
          -subj "/CN=somerootca ECDSA CA"

# server
openssl req -nodes \
          -newkey ec:nistp256.pem \
          -keyout server.key \
          -out server.req \
          -sha256 \
          -batch \
          -days 2000 \
          -subj "/CN=jobserver.com"

# client 'alice'
openssl req -nodes \
          -newkey ec:nistp384.pem \
          -keyout alice.key \
          -out alice.req \
          -sha256 \
          -batch \
          -days 2000 \
          -subj "/CN=alice/UID=alice"

# client 'bob'
openssl req -nodes \
          -newkey ec:nistp384.pem \
          -keyout bob.key \
          -out bob.req \
          -sha256 \
          -batch \
          -days 2000 \
          -subj "/CN=bob/UID=bob"

# client 'charlie'
openssl req -nodes \
          -newkey ec:nistp384.pem \
          -keyout charlie.key \
          -out charlie.req \
          -sha256 \
          -batch \
          -days 2000 \
          -subj "/CN=charlie/UID=charlie"

# unauthenticated client 'Eve' - signs her own cert, but could just be any cert not signed by a CA we trust
openssl req -nodes \
          -x509 \
          -newkey ec:nistp384.pem \
          -keyout eve.key \
          -out eve.pem \
          -sha256 \
          -batch \
          -days 3650 \
          -subj "/CN=eve/UID=eve"

# sign server cert
openssl x509 -req \
        -in server.req \
        -out server.pem \
        -CA ca.pem \
        -CAkey ca.key \
        -sha256 \
        -days 2000 \
        -set_serial 456 \
        -extensions v3_end -extfile openssl.cnf

# sign alice's cert
openssl x509 -req \
        -in alice.req \
        -out alice.pem \
        -CA ca.pem \
        -CAkey ca.key \
        -sha256 \
        -days 2000 \
        -set_serial 789 \
        -extensions v3_client -extfile openssl.cnf

# sign bob's cert
openssl x509 -req \
        -in bob.req \
        -out bob.pem \
        -CA ca.pem \
        -CAkey ca.key \
        -sha256 \
        -days 2000 \
        -set_serial 789 \
        -extensions v3_client -extfile openssl.cnf

# sign charlie's cert
openssl x509 -req \
        -in charlie.req \
        -out charlie.pem \
        -CA ca.pem \
        -CAkey ca.key \
        -sha256 \
        -days 2000 \
        -set_serial 789 \
        -extensions v3_client -extfile openssl.cnf

# eve's cert is signed by herself, so she shouldn't authenticate to our server
cat ca.pem > server.chain
cat server.pem ca.pem > server.fullchain

cat ca.pem > alice.chain
cat alice.pem ca.pem > alice.fullchain

openssl asn1parse -in ca.pem -out ca.der > /dev/null

