[package]
name = "joblib"
version = "0.0.1"
edition = "2021"

[dependencies]
bytes = "1.0"
futures = "0.3"
tokio = { version = "1.0", features = ["full"] }
uuid = { version = "0.8", features = ["v4"] }
thiserror = "1.0"
