[package]
name = "joblib"
version = "0.0.1"
edition = "2021"

[dependencies]
bytes = "1.1.0"
futures = "0.3.21"
tokio = { version = "1.17.0", features = ["full"] }
uuid = { version = "0.8.2", features = ["v4"] }
thiserror = "1.0.0"
